language: node_js
node_js:
  - node
addons:
  sshknownhosts:
    - 104.24.123.188
branches:
  only:
    - master
cache:
  directories:
    - .cache
before_install:
  - openssl aes-256-cbc -K $encrypted_b0d51b9ff91b_key -iv $encrypted_b0d51b9ff91b_iv -in deploy.enc -out deploy -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy
  - echo -e "Host {SERVER_IP}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add deploy
before_script:
  - export TZ=Europe/London
script:
  - npm run build
after_success:
  - set -x
  - tar -czvf file.tgz _site/*
  - scp -i deploy -P $port file.tgz $username@$host:$path
  - ssh -i deploy -p $port $username@$host $path/$file
