language: node_js
node_js:
  - node
addons:
  sshknownhosts:
    - 104.24.123.188
branches:
  only:
    - master
cache:
  directories:
    - .cache
before_install:
  - openssl aes-256-cbc -K $encrypted_b0d51b9ff91b_key -iv $encrypted_b0d51b9ff91b_iv -in deploy.enc -out deploy -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy
before_script:
  - export TZ=Europe/London
script:
  - npm run build
after_success:
  - tar -czvf file.tgz _site/*
  - scp -i deploy -o stricthostkeychecking=no -P $port file.tgz $username@$host:$path
  - ssh -i deploy -o stricthostkeychecking=no -p $port $username@$host $path/$file
