language: node_js
node_js:
  - node
addons:
  sshknownhosts:
    - 104.24.123.188
branches:
  only:
    - master
cache:
  directories:
    - .cache
before_script:
  - export TZ=Europe/London
script:
  - npm run build
after_success:
  - tar -czvf file.tgz _site/*
  - scp -P $port -o stricthostkeychecking=no file.tgz $username@$host:$path
  - ssh -p $port $username@$host $path/$file
