language: ruby

rvm:
- 2.1

addons:
  apt:
    packages:
    - sshpass

install:
- gem install bundler
- bundle install
- nvm install 5.4.1
- npm install
- gem install jekyll

before_script:
- npm install -g gulp-cli

script:
- gulp
- bundle exec jekyll build

cache:
  bundler: true
  directories:
  - node_modules

branches:
  only:
  - master

after_success:
- tar -czvf chrisburnell.tgz _site/*
- export SSHPASS=$DEPLOY_PASSWORD
- sshpass -e scp -P $DEPLOY_PORT -o stricthostkeychecking=no chrisburnell.tgz $DEPLOY_USERNAME@$DEPLOY_HOST:$DEPLOY_PATH
- sshpass -e ssh -p $DEPLOY_PORT $DEPLOY_USERNAME@$DEPLOY_HOST $DEPLOY_PATH/$DEPLOY_FILE
