title:        Chris Burnell
short_title:  cb
tagline:      'I’m Ravenous for CSS.'
lede:         'I’m a <span class="canada">Canadian</span> Front-End Developer living in London, UK. This is where I write about and share my passions: CSS, best practices and standards, web performance, front-end development, innovations on the web, sharing knowledge, and owning your content.'
color:        5f8aa6
color_scheme: false

author:
  name:        Chris Burnell
  shortname:   chrisburnell
  nationality: Canadian
  location:    London, UK
  email:       me@chrisburnell.com
  role:        Front-End Developer
  pgp:         9604F098260A0057
  codepen:     chrisburnell
  github:      chrisburnell
  gitlab:      chrisburnell
  mastodon:    chrisburnell@mastodon.social
  twitter:     iamchrisburnell
  untappd:     chrisburnell
  employer:
    name: Squiz
    url:  https://www.squiz.net
    role: Front-End Developer

urls:
  buymeacoffee:       https://www.buymeacoffee.com/8mtx3EQfI
  codepen:            https://codepen.io/chrisburnell
  gist:               https://gist.github.com/chrisburnell
  github:             https://github.com/chrisburnell
  github_repo:        https://github.com/chrisburnell/chrisburnell.com
  gitlab:             https://gitlab.com/chrisburnell
  lastfm:             https://last.fm/user/chrisburnell
  license:            https://www.gnu.org/licenses/gpl-3.0.txt
  londonwebstandards: https://londonwebstandards.org
  mastodon:           https://mastodon.social/@chrisburnell
  micropub:           https://micropub.chrisburnell.com
  microsub:           https://aperture.p3k.io/microsub/69
  notist:             https://noti.st/chrisburnell
  atom:               /feed.xml
  atom_articles:      /feed-articles.xml
  atom_bookmarks:     /feed-bookmarks.xml
  atom_notes:         /feed-notes.xml
  atom_pens:          /feed-pens.xml
  atom_talks:         /feed-talks.xml
  atom_recipes:       /feed-recipes.xml
  atom_reviews:       /feed-reviews.xml
  speakerdeck:        https://speakerdeck.com/chrisburnell
  spotify:            https://open.spotify.com/user/bcsc0akutj85l9p565n57u58z
  stateofthebrowser:  https://stateofthebrowser.com
  superfeedr:         https://chrisburnell.superfeedr.com/
  switchboard:        https://switchboard.p3k.io/
  twitter:            https://twitter.com/iamchrisburnell
  untappd:            https://untappd.com/user/chrisburnell
  webring:            https://🕸💍.ws/💘🇹🇫
  websub:             '@chrisburnell.com@chrisburnell.com'

sitemap:
  changefreq: monthly
  priority:   0.5

codepen:
  page: details
  themes:
    default: 119
    tabfree: 8863

url:      https://chrisburnell.com
baseurl:  '/'
live_url: https://chrisburnell.com
shorturl: https://repc.co/

detach: false
host: 127.0.0.1
port: 9001

timezone: Europe/London
language: en

show_drafts: false
future: true
unpublished: false
incremental: true
destination: ./_site
permalink: /:categories/:title/

feed_limit: 25

emptyArray: []

collections:
  beer:
    output: true
    permalink: /beer/:path/
  books:
    output: true
    permalink: /bookshelf/:path/
  likes:
    output: true
    permalink: /like/:path/
  music:
    output: true
    permalink: /music/:path/

defaults:
- scope:
    path: ''
    type: 'pages'
  values:
    layout: 'page'
- scope:
    path: '_drafts'
  values:
    layout: 'draft'
- scope:
    path: '_posts'
  values:
    layout: 'post'
    webmentions: true
- scope:
    path: ''
    type: 'beer'
  values:
    layout: 'page'
- scope:
    path: ''
    type: 'books'
  values:
    layout: 'page'
- scope:
    path: ''
    type: 'likes'
  values:
    layout: 'like'
- scope:
    path: ''
    type: 'music'
  values:
    layout: 'music'

keep_files:
- css
- js
- fonts
- images

exclude:
- CNAME
- CODE_OF_CONDUCT.md
- COMMIT_TEMPLATE.md
- CONTRIBUTING.md
- Gemfile
- gulpfile.babel.js
- ISSUE_TEMPLATE.md
- LICENSE
- node_modules
- package.json
- package-lock.json
- PULL_REQUEST_TEMPLATE.md
- README.md
- src
- vendor

plugins:
- jekyll-include-cache
- jekyll-mentions
- jekyll-redirect-from

jekyll-mentions:
  base_url: https://twitter.com
