title:        Chris Burnell
short_title:  cb
tagline:      'I’m Ravenous for CSS.'
lede:         'I’m a <span class="canada">Canadian</span> Front-End Developer living in London, UK. This is where I write about and share my passions: CSS, front-end development, innovating on the web, best practices and standards, learning, performance, IndieWeb, and owning your content.'
color:        5f8aa6
color_scheme: false

author:
  name:        Chris Burnell
  shortname:   chrisburnell
  nationality: Canadian
  location:    London, UK
  email:       me@chrisburnell.com
  role:        Front-End Developer
  pgp:         9604F098260A0057
  codepen:     chrisburnell
  github:      chrisburnell
  gitlab:      chrisburnell
  mastodon:    chrisburnell@mastodon.social
  twitter:     iamchrisburnell
  untappd:     chrisburnell
  employer:
    name: Squiz
    url:  https://www.squiz.net
    role: Front-End Developer

urls:
  feed:               /feed.xml
  buymeacoffee:       https://www.buymeacoffee.com/8mtx3EQfI
  codepen:            https://codepen.io/chrisburnell
  gist:               https://gist.github.com/chrisburnell
  github:             https://github.com/chrisburnell
  github_repo:        https://github.com/chrisburnell/chrisburnell.com
  gitlab:             https://gitlab.com/chrisburnell
  lastfm:             https://last.fm/user/chrisburnell
  license:            https://www.gnu.org/licenses/gpl-3.0.txt
  londonwebstandards: https://londonwebstandards.org
  mastodon:           https://mastodon.social/@chrisburnell
  micropub:           https://micropub.chrisburnell.com
  microsub:           https://aperture.p3k.io/microsub/69
  notist:             https://noti.st/chrisburnell
  speakerdeck:        https://speakerdeck.com/chrisburnell
  spotify:            https://open.spotify.com/user/bcsc0akutj85l9p565n57u58z
  stateofthebrowser:  https://stateofthebrowser.com
  superfeedr:         https://chrisburnell.superfeedr.com/
  switchboard:        https://switchboard.p3k.io/
  twitter:            https://twitter.com/iamchrisburnell
  untappd:            https://untappd.com/user/chrisburnell/
  webring:            https://🕸💍.ws/💘🇹🇫
  websub:             '@chrisburnell.com@chrisburnell.com'

sitemap:
  changefreq: monthly
  priority:   0.5

codepen:
  page: details
  themes:
    default: 119
    tabfree: 8863

url:        https://chrisburnell.com
baseurl:    '/'
live_url:   https://chrisburnell.com
static_url: https://chrisburnell.com/static/
shorturl:   https://repc.co/

detach: false
host: 127.0.0.1

timezone: Europe/London
language: en

show_drafts: false
future: true
unpublished: false
incremental: true
destination: ./_site
permalink: /:categories/:title/

paginate: 16
paginate_path: "/:num/"
feed_limit: 24

emptyArray: []

defaults:
- scope:
    type: 'pages'
  values:
    layout: 'page'
- scope:
    type: 'drafts'
  values:
    layout: 'draft'
    mf_root: 'entry'
- scope:
    type: 'posts'
  values:
    layout: 'post'
    mf_root: 'entry'
    webmentions: true
- scope:
    type: 'posts'
    path: '_posts/articles'
  values:
    category: 'article'
    prefix: a
- scope:
    type: 'posts'
    path: '_posts/beer'
  values:
    category: 'beer'
    layout: 'review'
    mf_root: 'review'
    mf_property: 'pk-drank'
    prefix: b
    emoji: '🍺'
    hidden: true
- scope:
    type: 'posts'
    path: '_posts/bookmarks'
  values:
    category: 'bookmark'
    mf_property: 'bookmark-of'
    prefix: h
    emoji: '🔖'
- scope:
    type: 'posts'
    path: '_posts/books'
  values:
    category: 'book'
    layout: 'review'
    mf_root: 'review'
    mf_property: 'read-of'
    prefix: r
    emoji: '📖'
    ignore: true
- scope:
    type: 'posts'
    path: '_posts/food'
  values:
    category: 'food'
    layout: 'review'
    mf_root: 'review'
    mf_property: 'pk-ate'
    prefix: e
    emoji: '🍛'
    hidden: true
    ignore: true
- scope:
    type: 'posts'
    path: '_posts/likes'
  values:
    category: 'like'
    mf_property: 'like-of'
    prefix: f
    emoji: '❤️'
    hidden: true
    ignore: true
- scope:
    type: 'posts'
    path: '_posts/movies'
  values:
    category: 'movie'
    layout: 'review'
    mf_root: 'review'
    mf_property: 'watch-of'
    emoji: '🎬'
    hidden: true
    ignore: true
- scope:
    type: 'posts'
    path: '_posts/music'
  values:
    category: 'music'
    layout: 'review'
    mf_root: 'review'
    mf_property: 'listen-of'
    prefix: m
    emoji: '🎶'
    ignore: true
- scope:
    type: 'posts'
    path: '_posts/notes'
  values:
    category: 'note'
    prefix: t
- scope:
    type: 'posts'
    path: '_posts/pens'
  values:
    category: 'pen'
    prefix: c
    comments: codepen
    emoji: '✒️'
- scope:
    type: 'posts'
    path: '_posts/podcasts'
  values:
    category: 'podcast'
    layout: 'review'
    mf_root: 'review'
    mf_property: 'listen-of'
    prefix: l
    emoji: '🎙'
    hidden: true
    ignore: true
- scope:
    type: 'posts'
    path: '_posts/recipes'
  values:
    category: 'recipe'
    prefix: d
    emoji: '📝'
    hidden: true
    ignore: true
- scope:
    type: 'posts'
    path: '_posts/talks'
  values:
    category: 'talk'
    prefix: s
    emoji: '🗣'
- scope:
    type: 'posts'
    path: '_posts/travel'
  values:
    category: 'travel'
    prefix: g
    emoji: '✈️'
    hidden: true
    ignore: true
- scope:
    type: 'posts'
    path: '_posts/tv'
  values:
    category: 'tv'
    layout: 'review'
    mf_root: 'review'
    mf_property: 'watch-of'
    emoji: '📺'
    hidden: true
    ignore: true

keep_files:
- css
- js
- fonts
- images

exclude:
- CNAME
- CODE_OF_CONDUCT.md
- COMMIT_TEMPLATE.md
- CONTRIBUTING.md
- Gemfile
- gulpfile.babel.js
- ISSUE_TEMPLATE.md
- LICENSE
- node_modules
- package.json
- package-lock.json
- PULL_REQUEST_TEMPLATE.md
- README.md
- src
- vendor

plugins:
- jekyll-include-cache
- jekyll-mentions
- jekyll-paginate
- jekyll-redirect-from

jekyll-mentions:
  base_url: https://twitter.com
