name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "01 1 * * *"
    - cron: "01 13 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from git
        uses: actions/checkout@master
      - name: Use Node.js 19.0.0
        uses: actions/setup-node@v1
        with:
          node-version: "19.0.0"
      - name: Cache npm dependencies
        id: cache_npm
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
      - name: Cache eleventy assets
        id: cache_eleventy
        uses: actions/cache@v2
        with:
          path: |
            .cache
            _site/images
          key: ${{ runner.OS }}-site-cache-${{ hashFiles('**/lockfiles') }}
      - name: Set the timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Europe/London
      - name: Install npm modules
        run: npm ci
      - name: Build website
        run: npm run build
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          ELEVENTY_PRODUCTION: true
          ODESLI_URL: ${{ secrets.ODESLI_TOKEN }}
          PERSONAL_API_URL: ${{ secrets.PERSONAL_API_URL }}
          PERSONAL_API_TOKEN: ${{ secrets.PERSONAL_API_TOKEN }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          WEBMENTION_IO_TOKEN: ${{ secrets.WEBMENTION_IO_TOKEN }}
      - name: Copy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          rm: true
          source: "_site/*"
          target: "${{ secrets.DEPLOY_PATH }}build"
          strip_components: 1
      - name: Post-action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: "${{ secrets.DEPLOY_PATH }}${{ secrets.DEPLOY_FILE }}"
